apiVersion: v1
kind: Service
metadata:
  name: {{ include "mentor-bot.fullname" . }}-service
  labels:
    {{- include "mentor-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mentor-bot.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.portName }}
    protocol: {{ .Values.service.protocol }}
  sessionAffinity: None
